package Hospital_Management.MIDDLE_LAYER;

public enum Department {
    
    DERMATOLOGIST, HEMATOLOGIST, NEUROLOGIST, PATHOLOGIST , SPORTS_MEDICINE , CARDIOLOGIST , PSYCHIATRIST, DENTIST , ONCOLOGIST;
}
